"""baseline

Revision ID: 04b66e98b560
Revises: 
Create Date: 2026-08-29 11:28:13.390848
"""
from alembic import op
import sqlalchemy as sa


revision = '04b66e98b560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('artist_id', sa.String(length=40), nullable=True),
    sa.Column('album_id', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_albums_artist_name'), 'artist_albums', ['artist_name'], unique=False)
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('deezer_id', sa.String(length=40), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('nb_fan', sa.Integer(), nullable=True),
    sa.Column('nb_album', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('gain_db', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('era', sa.String(length=10), nullable=True),
    sa.Column('is_remix', sa.Boolean(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('feat', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('artist_image_url', sa.Text(), nullable=True),
    sa.Column('artist_image_path', sa.Text(), nullable=True),
    sa.Column('deezer_id', sa.String(length=40), nullable=True),
    sa.Column('album_id', sa.String(length=40), nullable=True),
    sa.Column('artist_id', sa.String(length=40), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index('ix_tracks_bpm_energy', 'tracks', ['bpm', 'energy'], unique=False)
    op.create_index(op.f('ix_tracks_deezer_id'), 'tracks', ['deezer_id'], unique=True)
    op.create_index(op.f('ix_tracks_era'), 'tracks', ['era'], unique=False)
    op.create_index('ix_tracks_era_energy', 'tracks', ['era', 'energy'], unique=False)
    op.create_index(op.f('ix_tracks_genre'), 'tracks', ['genre'], unique=False)
    op.create_index('ix_tracks_genre_year', 'tracks', ['genre', 'year'], unique=False)
    op.create_index(op.f('ix_tracks_language'), 'tracks', ['language'], unique=False)
    op.create_index(op.f('ix_tracks_title'), 'tracks', ['title'], unique=False)
    op.create_index(op.f('ix_tracks_year'), 'tracks', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist_name', name='uq_follow')
    )
    op.create_index(op.f('ix_follows_artist_name'), 'follows', ['artist_name'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.create_table('mixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('seed', sa.String(length=80), nullable=True),
    sa.Column('tracks_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mixes_user_id'), 'mixes', ['user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_user_id'), 'playlists', ['user_id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('seconds_listened', sa.Float(), nullable=True),
    sa.Column('context', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_played_at'), 'plays', ['played_at'], unique=False)
    op.create_index(op.f('ix_plays_track_id'), 'plays', ['track_id'], unique=False)
    op.create_index(op.f('ix_plays_user_id'), 'plays', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_track')
    )
    op.create_index(op.f('ix_reactions_track_id'), 'reactions', ['track_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.create_table('similar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_a', sa.Integer(), nullable=True),
    sa.Column('track_b', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_a'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['track_b'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_a', 'track_b', name='uq_similar')
    )
    op.create_index('ix_similar_a_score', 'similar', ['track_a', 'score'], unique=False)
    op.create_index(op.f('ix_similar_track_a'), 'similar', ['track_a'], unique=False)
    op.create_table('smart_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taste_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('preferred_genres', sa.Text(), nullable=True),
    sa.Column('preferred_artists', sa.Text(), nullable=True),
    sa.Column('preferred_eras', sa.Text(), nullable=True),
    sa.Column('bpm_mean', sa.Float(), nullable=True),
    sa.Column('energy_mean', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_profile_user_id'), 'taste_profile', ['user_id'], unique=True)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', name='uq_pt')
    )
    op.create_index(op.f('ix_playlist_tracks_playlist_id'), 'playlist_tracks', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_tracks_track_id'), 'playlist_tracks', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_tracks_track_id'), table_name='playlist_tracks')
    op.drop_index(op.f('ix_playlist_tracks_playlist_id'), table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index(op.f('ix_taste_profile_user_id'), table_name='taste_profile')
    op.drop_table('taste_profile')
    op.drop_table('smart_playlists')
    op.drop_index(op.f('ix_similar_track_a'), table_name='similar')
    op.drop_index('ix_similar_a_score', table_name='similar')
    op.drop_table('similar')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_track_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_plays_user_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_track_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_played_at'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_playlists_user_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_mixes_user_id'), table_name='mixes')
    op.drop_table('mixes')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_artist_name'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracks_year'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_language'), table_name='tracks')
    op.drop_index('ix_tracks_genre_year', table_name='tracks')
    op.drop_index(op.f('ix_tracks_genre'), table_name='tracks')
    op.drop_index('ix_tracks_era_energy', table_name='tracks')
    op.drop_index(op.f('ix_tracks_era'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_deezer_id'), table_name='tracks')
    op.drop_index('ix_tracks_bpm_energy', table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_artist_albums_artist_name'), table_name='artist_albums')
    op.drop_table('artist_albums')
    # ### end Alembic commands ###
